
# cargo-vet config file

[cargo-vet]
version = "0.10"

[imports.bytecode-alliance]
url = "https://raw.githubusercontent.com/bytecodealliance/wasmtime/main/supply-chain/audits.toml"

[imports.google]
url = "https://raw.githubusercontent.com/google/supply-chain/main/audits.toml"

[imports.isrg]
url = "https://raw.githubusercontent.com/divviup/libprio-rs/main/supply-chain/audits.toml"

[imports.mozilla]
url = "https://raw.githubusercontent.com/mozilla/supply-chain/main/audits.toml"

[imports.zcash]
url = "https://raw.githubusercontent.com/zcash/rust-ecosystem/main/supply-chain/audits.toml"

[[exemptions.blake3]]
version = "1.8.4"
criteria = "safe-to-deploy"

[[exemptions.cc]]
version = "1.2.59"
criteria = "safe-to-deploy"

[[exemptions.constant_time_eq]]
version = "0.4.2"
criteria = "safe-to-deploy"

[[exemptions.convert_case]]
version = "0.11.0"
criteria = "safe-to-deploy"

[[exemptions.cpufeatures]]
version = "0.3.0"
criteria = "safe-to-deploy"

[[exemptions.fastrand]]
version = "2.4.0"
criteria = "safe-to-deploy"

[[exemptions.find-msvc-tools]]
version = "0.1.9"
criteria = "safe-to-deploy"

[[exemptions.getrandom]]
version = "0.3.4"
criteria = "safe-to-deploy"

[[exemptions.libredox]]
version = "0.1.15"
criteria = "safe-to-deploy"

[[exemptions.once_cell]]
version = "1.21.4"
criteria = "safe-to-deploy"

[[exemptions.plain]]
version = "0.2.3"
criteria = "safe-to-deploy"

[[exemptions.ppv-lite86]]
version = "0.2.21"
criteria = "safe-to-deploy"

[[exemptions.proptest]]
version = "1.11.0"
criteria = "safe-to-deploy"

[[exemptions.proptest-derive]]
version = "0.8.0"
criteria = "safe-to-deploy"

[[exemptions.proptest-macro]]
version = "0.5.0"
criteria = "safe-to-deploy"

[[exemptions.quick-error]]
version = "1.2.3"
criteria = "safe-to-deploy"

[[exemptions.r-efi]]
version = "5.3.0"
criteria = "safe-to-deploy"

[[exemptions.rand_xorshift]]
version = "0.4.0"
criteria = "safe-to-deploy"

[[exemptions.redox_syscall]]
version = "0.7.3"
criteria = "safe-to-deploy"

[[exemptions.rusty-fork]]
version = "0.3.1"
criteria = "safe-to-deploy"

[[exemptions.tempfile]]
version = "3.27.0"
criteria = "safe-to-deploy"

[[exemptions.unarray]]
version = "0.1.4"
criteria = "safe-to-deploy"

[[exemptions.zerocopy]]
version = "0.8.48"
criteria = "safe-to-deploy"

[[exemptions.zerocopy-derive]]
version = "0.8.48"
criteria = "safe-to-deploy"

[[exemptions.zstd]]
version = "0.13.3"
criteria = "safe-to-deploy"

[[exemptions.zstd-safe]]
version = "7.2.4"
criteria = "safe-to-deploy"

[[exemptions.zstd-sys]]
version = "2.0.16+zstd.1.5.7"
criteria = "safe-to-deploy"
